config/routes.rb
CrdSiteJrc::Application.routes.draw do

  match '/curso',  to: 'static_pages#curso'

  match '/contacto',  to: 'static_pages#contacto'

  root to: 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def curso
  end

  def contacto
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_browsercheck.html.erb
<!--[if lt IE 9 ]>
	<div class="alert alert-block">
  		<button type="button" class="close" data-dismiss="alert">&times;</button>
  		<h4>Importante!</h4>
  		Seu navegador está desatualizado. Ele possui falhas de segurança e pode apresentar problemas para exibir este e outros websites.
  		Recomendamos que actualize o seu navegador <a target='_blank' href='http://whatbrowser.org/'>aqui</a>.
	</div>
<![endif]-->

app/views/layouts/_footer.html.erb
<footer>
	<!--<hr class="featurette-divider">-->
	<div class="container">
		<div class="row">
			<div class="span6">developed by <b><a href="http://cristheinz.info" target="_blank">cristheinz</a></b></div>
		</div>

		<div class="row">
			<center>
				<br />
				<small><%= Time.now.year %> - Copyright</small>
			</center>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="container">
  <div class="row">
    <div class="span6">
      <p>
      	<span id="brand" class="crd-brand crd-fade">Junior Rodriguez</span><br/>
      	<span id="brand2" class="crd-fade2">Hair Styling &amp; Body Clinic</span>
      </p>
    </div>
    <div class="span6">
      <ul class="nav nav-pills nav-stacked visible-phone">
      	<li class="active"><%= link_to "Sobre Nós", root_path %></li>
        <li><%= link_to "Cursos", curso_path %></li>
        <li><%= link_to "Contactos", contacto_path %></li>
      </ul>
      
      <ul id="nav" class="crd-nav nav nav-pills hidden-phone fadeInLeftBig">
        <li class="active"><%= link_to "Sobre Nós", root_path(root: '1'), :'data-toggle' => "pill", :'data-target' => "#", class: "root" %></li>
        <li><%= link_to "Cursos", curso_path, :'data-toggle' => "pill", :'data-target' => "#" %></li>
        <li><%= link_to "Contactos", contacto_path, :'data-toggle' => "pill", :'data-target' => "#" %></li>
      </ul>

    </div>
  </div>
</header>

<script>
var url = window.location;

$('ul.nav > li').removeClass('active');
// Will only work if string in href matches with location
$('ul.nav a[href="'+ url +'"]').parent().addClass('active');

// Will also work for relative and absolute hrefs
$('ul.nav a').filter(function() {
    return this.href == url;
}).parent().addClass('active');


if(location.pathname != "/" || window.location.href.indexOf("root") > -1) {
  $('#brand').removeClass('crd-fade');
  $('#brand2').removeClass('crd-fade2');
  $('#nav').removeClass('fadeInLeftBig');
  /*if(window.location.href.indexOf("root") > -1)
    $('.root').parent().addClass('active');*/
}

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hair Styling and Body Clinic</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">
		<%= render 'layouts/header' %>
 		<div id="main" class="container">
   			<%= render 'layouts/browsercheck' %>
   			<div class="row">
				<div class="span9 offset2 crd-box crd-flash">
   					<%= yield %>
   				</div>
   			</div>
		 </div>
		 <%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/static_pages/contacto.html.erb
<h1>StaticPages#contacto</h1>
<p>Find me in app/views/static_pages/contacto.html.erb</p>

app/views/static_pages/curso.html.erb
<h1>StaticPages#curso</h1>
<p>Find me in app/views/static_pages/curso.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>